import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import DashboardLayout from './layout';
import OwnerDocumentsWorkspace from './components/OwnerDocumentsWorkspace';
import OwnerDocumentDetail from './components/OwnerDocumentDetail';
import OwnerAuditWorkspace from './components/OwnerAuditWorkspace';
import OwnerSettingsWorkspace from './components/OwnerSettingsWorkspace';

process.env.NEXT_PUBLIC_ENGINE_URL = 'http://api.test'; const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } }); const asOf = '2026-07-21T12:00:00.000Z'; const document = (visibility: 'visible' | 'revoked' = 'visible') => ({ id: 'doc-1', title: 'Launch plan', documentType: 'deliverable', client: { id: 'client-1', name: 'Acme' }, project: null, visibility, createdAt: asOf, revokedAt: visibility === 'revoked' ? asOf : null }); const bootstrap = { success: true, data: { identity: { email: 'owner@example.test' }, capabilities: { overview: 'available' } } }; const dashboard = { success: true, data: { asOf, window: 'today', metrics: [], attention: { label: 'Attention', status: 'unavailable', source: 'owner', window: 'current', asOf, reason: 'Unavailable', items: [] }, recentActivity: { label: 'Activity', status: 'unavailable', source: 'owner', window: 'current', asOf, reason: 'Unavailable', items: [] }, health: { label: 'Health', status: 'unavailable', source: 'owner', window: 'current', asOf, reason: 'Unavailable' } } }; let nativeFetch = globalThis.fetch;
afterEach(() => { cleanup(); globalThis.fetch = nativeFetch; vi.restoreAllMocks(); });
function ownerFetch() { let revoked = false; const fetch = vi.fn(async (input: RequestInfo | URL, init: RequestInit = {}) => { const url = input.toString(); if (url.endsWith('/api/auth/refresh')) return json({ accessToken: 'token' }); if (url.endsWith('/bootstrap')) return json(bootstrap); if (url.endsWith('/dashboard')) return json(dashboard); if (url.includes('/documents/doc-1')) { if (init.method === 'DELETE') { revoked = true; return json({ success: true, data: document('revoked') }); } return json({ success: true, data: document(revoked ? 'revoked' : 'visible') }); } if (url.includes('/documents') && init.method === 'POST') return json({ success: true, data: document() }, 201); if (url.includes('/documents')) return json({ success: true, data: { items: [document()], pageInfo: { nextCursor: 'MQ', hasNextPage: true } } }); if (url.includes('/audit')) return json({ success: true, data: { items: [{ id: 'audit-1', label: 'Client Portal document published', category: 'documents', action: 'publish', success: true, resourceType: 'client_portal_document', resourceId: 'doc-1', createdAt: asOf }], pageInfo: { nextCursor: null, hasNextPage: false } } }); if (url.includes('/settings/status')) return json({ success: true, data: { asOf, api: { label: 'Owner Workspace API', status: 'available', source: 'request', asOf, value: 'reachable' }, environment: { label: 'Runtime environment', status: 'available', source: 'runtime', asOf, value: 'non-production' }, companyProfile: { label: 'Company profile', status: 'unavailable', source: 'crm', asOf, reason: 'No authoritative company profile source is configured.' }, branding: { label: 'Branding', status: 'unavailable', source: 'settings', asOf, reason: 'Unavailable' }, integrations: { label: 'Integrations', status: 'unavailable', source: 'integrations', asOf, reason: 'Unavailable' }, editableSettings: { label: 'Editable settings', status: 'unavailable', source: 'auth', asOf, reason: 'Unavailable' } } }); if (url.includes('/search')) return json({ success: true, data: { asOf, groups: [{ type: 'companies', status: 'available', items: [{ id: 'company-1', label: 'Acme', href: '/dashboard/crm?company=company-1' }] }, { type: 'leads', status: 'unavailable', items: [], reason: 'No searchable lead display field exists.' }] } }); return json({ error: { message: 'Unexpected request' } }, 500); }); globalThis.fetch = fetch as unknown as typeof fetch; return fetch; }
const workspace = (node: React.ReactNode) => render(<DashboardLayout>{node}</DashboardLayout>);

describe('Owner Workspace operations', () => {
  it('renders document filters, private publish, cursor pagination, and client-visibility revocation', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerDocumentsWorkspace />); expect(await screen.findByRole('heading', { name: 'Client Portal documents' })).toBeTruthy(); await user.type(screen.getByLabelText('Search documents'), 'Launch'); await user.click(screen.getByRole('button', { name: 'Apply' })); await user.click(await screen.findByRole('button', { name: 'Next page' })); await user.type(screen.getByLabelText('Document client ID'), 'client-1'); await user.type(screen.getByLabelText('Title'), 'Launch plan'); await user.upload(screen.getByLabelText('Document file'), new File(['plan'], 'plan.txt', { type: 'text/plain' })); fireEvent.submit(screen.getByRole('button', { name: 'Publish' }).closest('form')!); expect((fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>).some(([url, init]) => url.toString().includes('/documents') && init?.method === 'POST')).toBe(true); const urls = (fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).map(([url]) => url.toString()); expect(urls.some((url) => url.includes('q=Launch') && url.includes('cursor=MQ'))).toBe(true); expect(urls.every((url) => !url.includes('storage') && !url.includes('signed'))).toBe(true); cleanup(); workspace(<OwnerDocumentDetail documentId="doc-1" />); expect(await screen.findByRole('heading', { name: 'Launch plan' })).toBeTruthy(); await user.click(screen.getByRole('button', { name: 'Revoke client visibility' })); expect(await screen.findByText('revoked')).toBeTruthy(); });
  it('renders redacted audit and explicit settings states with accessible global search groups', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerAuditWorkspace />); expect(await screen.findByText('Client Portal document published')).toBeTruthy(); expect(screen.queryByText(/storage_path|127\.0\.0\.1/)).toBeNull(); cleanup(); workspace(<OwnerSettingsWorkspace />); expect(await screen.findByText('No authoritative company profile source is configured.')).toBeTruthy(); expect(screen.queryByRole('button', { name: /role|secret|environment/i })).toBeNull(); await user.click(screen.getByText('Search workspace')); await user.type(screen.getByLabelText('Search workspace records'), 'Acme'); await user.click(screen.getByRole('button', { name: 'Search' })); expect(await screen.findByRole('link', { name: 'Acme' })).toBeTruthy(); expect(screen.getByText('No searchable lead display field exists.')).toBeTruthy(); const urls = (fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).map(([url]) => url.toString()); expect(urls.some((url) => url.includes('/search?q=Acme'))).toBe(true); });
});
