import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import DashboardLayout from './layout';
import OwnerProjectsWorkspace from './components/OwnerProjectsWorkspace';
import OwnerProjectDetail from './components/OwnerProjectDetail';
import OwnerTasksWorkspace from './components/OwnerTasksWorkspace';

process.env.NEXT_PUBLIC_ENGINE_URL = 'http://api.test';
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const asOf = '2026-07-21T12:00:00.000Z'; const client = { id: 'client-1', name: 'Acme', created_at: asOf, updated_at: asOf }; const project = { id: 'project-1', name: 'Launch', client: { id: client.id, name: client.name }, status: { label: 'Project status', status: 'unavailable', source: 'crm_projects', window: 'current', asOf, reason: 'No authoritative project status field exists.' }, progress: { label: 'Project progress', status: 'unavailable', source: 'crm_projects', window: 'current', asOf, reason: 'No authoritative project progress field exists.' } }; const task = { id: 'task-1', name: 'Review', completed: false, assignee: null, project: { id: project.id, name: project.name, client: project.client }, status: { label: 'Task status', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'Completion is the only authoritative task-state field.' }, priority: { label: 'Task priority', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task priority field exists.' }, dueDate: { label: 'Task due date', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task due-date field exists.' }, progress: { label: 'Task progress', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task progress field exists.' } }; const employee = { id: 'employee-1', fullName: 'Ava Employee', email: 'ava@example.test', workload: { status: 'available', source: 'crm_tasks', window: 'current', asOf, definition: 'Direct assignments.', assigned: 0, open: 0, completed: 0 }, availability: project.status, performance: project.status };
const bootstrap = { success: true, data: { identity: { email: 'owner@example.test' }, capabilities: { overview: 'available' } } }; const dashboard = { success: true, data: { asOf, window: 'today', metrics: [], attention: { label: 'Attention', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable', items: [] }, recentActivity: { label: 'Activity', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable', items: [] }, health: { label: 'Health', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable' } } };
let nativeFetch = globalThis.fetch; afterEach(() => { cleanup(); globalThis.fetch = nativeFetch; vi.restoreAllMocks(); });
function ownerFetch() { const fetch = vi.fn(async (input: RequestInfo | URL, init: RequestInit = {}) => { const url = input.toString(); if (url.endsWith('/api/auth/refresh')) return json({ accessToken: 'token' }); if (url.endsWith('/bootstrap')) return json(bootstrap); if (url.endsWith('/dashboard')) return json(dashboard); if (url.includes('/clients?')) return json({ success: true, data: { items: [client], pageInfo: { nextCursor: null, hasNextPage: false } } }); if (url.includes('/employees?')) return json({ success: true, data: { items: [employee], pageInfo: { nextCursor: null, hasNextPage: false } } }); if (url.includes('/tasks?')) return json({ success: true, data: { items: [task], pageInfo: { nextCursor: 'MQ', hasNextPage: true } } }); if (url.includes('/projects/project-1/tasks/task-1')) return json({ success: true, data: task }); if (url.includes('/projects/project-1/tasks') && init.method === 'POST') return json({ success: true, data: task }, 201); if (url.includes('/projects/project-1') && init.method === 'PATCH') return json({ success: true, data: project }); if (url.includes('/projects/project-1')) return json({ success: true, data: { project, tasks: { items: [task], pageInfo: { nextCursor: null, hasNextPage: false } } } }); if (url.includes('/projects') && init.method === 'POST') return json({ success: true, data: project }, 201); if (url.includes('/projects')) return json({ success: true, data: { items: [project], pageInfo: { nextCursor: 'MQ', hasNextPage: true } } }); return json({ error: { message: 'Unexpected test request' } }, 500); }); globalThis.fetch = fetch as unknown as typeof fetch; return fetch; }
function workspace(node: React.ReactNode) { return render(<DashboardLayout>{node}</DashboardLayout>); }

describe('Owner Workspace projects', () => {
  it('creates and filters projects with scoped client selectors and cursor pagination', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectsWorkspace />); expect(await screen.findByRole('heading', { name: 'Project overview' })).toBeTruthy(); await user.selectOptions(await screen.findByLabelText('Project client'), client.id); await user.type(screen.getByLabelText('Project name'), 'Launch two'); await user.click(screen.getByRole('button', { name: 'Create project' })); expect((await screen.findByRole('status')).textContent).toContain('Project created.'); await user.type(screen.getByLabelText('Search projects'), 'Launch'); await user.selectOptions(screen.getByLabelText('Project client filter'), client.id); await user.click(screen.getByRole('button', { name: 'Apply' })); await user.click(await screen.findByRole('button', { name: 'Next page' })); const calls = fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>; expect(calls.some(([url]) => url.toString().includes('q=Launch') && url.toString().includes('client_id=client-1'))).toBe(true); expect(calls.some(([url]) => url.toString().includes('cursor=MQ'))).toBe(true); expect(JSON.parse(calls.find(([url, init]) => url.toString().endsWith('/projects') && init?.method === 'POST')?.[1]?.body as string)).toEqual({ client_id: client.id, name: 'Launch two' }); expect(screen.getByText(/No authoritative project progress field exists/)).toBeTruthy(); });
  it('edits project/task names, creates and completes tasks, and assigns a scoped employee', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectDetail projectId="project-1" />); expect(await screen.findByRole('heading', { name: 'Launch' })).toBeTruthy(); await user.clear(screen.getByLabelText('Edit project name')); await user.type(screen.getByLabelText('Edit project name'), 'Launch updated'); await user.click(screen.getByRole('button', { name: 'Save project name' })); expect((await screen.findByRole('status')).textContent).toContain('Project name updated.'); await user.click(screen.getByRole('button', { name: 'Mark complete' })); await user.type(screen.getByLabelText('New task name'), 'Ship'); await user.click(screen.getByRole('button', { name: 'Create task' })); await user.click(screen.getByText('Task details and assignment')); await user.clear(screen.getByLabelText('Edit task name for Review')); await user.type(screen.getByLabelText('Edit task name for Review'), 'Review updated'); await user.click(screen.getByRole('button', { name: 'Save task name' })); await user.click(screen.getByText('Task details and assignment')); await user.selectOptions(screen.getByLabelText('Employee for Review'), employee.id); await user.click(screen.getByRole('button', { name: 'Assign employee' })); await waitFor(() => expect((fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>).filter(([url, init]) => url.toString().includes('/tasks/task-1') && init?.method === 'PATCH').length).toBeGreaterThanOrEqual(3)); expect((fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).every(([url]) => !url.toString().includes('/employee-portal'))).toBe(true); });
});

describe('Owner Workspace task route', () => {
  it('creates, filters, paginates, and renames tasks with scoped projects', async () => {
    const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerTasksWorkspace />);
    expect(await screen.findByRole('heading', { name: 'Task workspace' })).toBeTruthy();
    await user.selectOptions(screen.getByLabelText('Task project'), project.id);
    await user.type(screen.getByLabelText('New task name'), 'Ship'); await user.click(screen.getByRole('button', { name: 'Create task' }));
    expect((await screen.findByRole('status')).textContent).toContain('Task created.');
    await user.clear(screen.getByLabelText('Edit task name for Review')); await user.type(screen.getByLabelText('Edit task name for Review'), 'Review updated'); await user.click(screen.getByRole('button', { name: 'Save task name' }));
    await user.type(screen.getByLabelText('Search tasks'), 'Review'); await user.selectOptions(screen.getByLabelText('Task project filter'), project.id); await user.click(screen.getByRole('button', { name: 'Apply' }));
    await user.click(await screen.findByRole('button', { name: 'Next page' }));
    const calls = fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>;
    expect(calls.some(([url]) => url.toString().includes('/tasks?') && url.toString().includes('q=Review') && url.toString().includes('project_id=project-1'))).toBe(true);
    expect(calls.some(([url]) => url.toString().includes('/tasks?') && url.toString().includes('cursor=MQ'))).toBe(true);
    expect(JSON.parse(calls.find(([url, init]) => url.toString().endsWith('/projects/project-1/tasks') && init?.method === 'POST')?.[1]?.body as string)).toEqual({ name: 'Ship' });
    expect(JSON.parse(calls.find(([url, init]) => url.toString().endsWith('/projects/project-1/tasks/task-1') && init?.method === 'PATCH')?.[1]?.body as string)).toEqual({ name: 'Review updated' });
  });
});