import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import DashboardLayout from './layout';
import OwnerProjectsWorkspace from './components/OwnerProjectsWorkspace';
import OwnerProjectDetail from './components/OwnerProjectDetail';

process.env.NEXT_PUBLIC_ENGINE_URL = 'http://api.test';
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const asOf = '2026-07-21T12:00:00.000Z'; const clientOption = { id: '30000000-0000-4000-8000-000000000003', client_code: 'JP-CLI-000001', name: 'Acme', created_at: asOf, updated_at: asOf };
const project = { id: 'project-1', name: 'Launch', client: { id: clientOption.id, name: 'Acme' }, status: { label: 'Project status', status: 'unavailable', source: 'crm_projects', window: 'current', asOf, reason: 'No authoritative project status field exists.' }, progress: { label: 'Project progress', status: 'unavailable', source: 'crm_projects', window: 'current', asOf, reason: 'No authoritative project progress field exists.' } }; const task = { id: 'task-1', name: 'Review', completed: false, assignee: null, project: { id: project.id, name: project.name, client: project.client }, status: { label: 'Task status', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'Completion is the only authoritative task-state field.' }, priority: { label: 'Task priority', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task priority field exists.' }, dueDate: { label: 'Task due date', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task due-date field exists.' }, progress: { label: 'Task progress', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task progress field exists.' } }; const employeeOption = { id: '60000000-0000-4000-8000-000000000006', employeeCode: 'JP-EMP-000001', fullName: 'Ava Owner', email: 'ava@example.test', status: 'active' }; const pendingEmployeeOption = { id: '70000000-0000-4000-8000-000000000007', employeeCode: 'JP-EMP-000002', fullName: 'Pending Employee', email: 'pending@example.test', status: 'pending_verification' };
const bootstrap = { success: true, data: { identity: { email: 'owner@example.test' }, capabilities: { overview: 'available' } } }; const dashboard = { success: true, data: { asOf, window: 'today', metrics: [], attention: { label: 'Attention', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable', items: [] }, recentActivity: { label: 'Activity', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable', items: [] }, health: { label: 'Health', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable' } } };
let nativeFetch = globalThis.fetch; afterEach(() => { cleanup(); globalThis.fetch = nativeFetch; vi.restoreAllMocks(); });
function ownerFetch() { const fetch = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = input.toString(); if (url.endsWith('/api/auth/refresh')) return json({ accessToken: 'token' }); if (url.endsWith('/bootstrap')) return json(bootstrap); if (url.endsWith('/dashboard')) return json(dashboard); if (url.includes('/clients?')) return json({ success: true, data: { items: [clientOption], pageInfo: { nextCursor: null, hasNextPage: false } } }); if (url.includes('/employees?')) return json({ success: true, data: { items: [employeeOption, pendingEmployeeOption], pageInfo: { nextCursor: null, hasNextPage: false } } }); if (url.includes('/projects/project-1/tasks/task-1')) return json({ success: true, data: task }); if (url.includes('/projects/project-1/tasks') && init?.method === 'POST') return json({ success: true, data: task }, 201); if (url.includes('/projects/project-1')) return json({ success: true, data: { project, tasks: { items: [task], pageInfo: { nextCursor: null, hasNextPage: false } } } }); if (url.includes('/projects')) return json({ success: true, data: { items: [project], pageInfo: { nextCursor: 'MQ', hasNextPage: true } } }); return json({ error: { message: 'Unexpected test request' } }, 500); }); globalThis.fetch = fetch as unknown as typeof fetch; return fetch; }
function workspace(node: React.ReactNode) { return render(<DashboardLayout>{node}</DashboardLayout>); }

describe('Owner Workspace projects', () => {
  it('renders a searchable, filterable, cursor-paginated project overview with unavailable progress fidelity', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectsWorkspace />); expect(await screen.findByRole('heading', { name: 'Project overview' })).toBeTruthy(); await user.type(screen.getByLabelText('Search projects'), 'Launch'); await user.type(screen.getByLabelText('Project client ID filter'), clientOption.id); await user.click(screen.getByRole('button', { name: 'Apply' })); await user.click(await screen.findByRole('button', { name: 'Next page' })); const urls = (fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).map(([url]) => url.toString()); expect(urls.some((url) => url.includes('q=Launch') && url.includes(`client_id=${clientOption.id}`))).toBe(true); expect(urls.some((url) => url.includes('cursor=MQ'))).toBe(true); expect(screen.getByText(/No authoritative project progress field exists/)).toBeTruthy(); });
  it('supports existing task creation, owner completion, and active-employee assignment without Employee Portal access', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectDetail projectId="project-1" />); expect(await screen.findByRole('heading', { name: 'Launch' })).toBeTruthy(); await user.click(screen.getByRole('button', { name: 'Mark complete' })); expect((await screen.findByRole('status')).textContent).toContain('Task completed.'); await user.type(screen.getByLabelText('Task name'), 'Ship'); await user.click(screen.getByRole('button', { name: 'Create task' })); await user.click(screen.getByText('Task details and assignment')); await user.selectOptions(await screen.findByLabelText('Active employee for Review'), employeeOption.id); expect(screen.getByRole('option', { name: /Ava Owner \(JP-EMP-000001\)/ })).toBeTruthy(); expect(screen.queryByRole('option', { name: /Pending Employee \(JP-EMP-000002\)/ })).toBeNull(); await user.click(screen.getByRole('button', { name: 'Assign employee' })); await waitFor(() => { const request = (fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>).find(([url, init]) => url.toString().includes('/tasks/task-1') && init?.method === 'PATCH' && JSON.parse(init.body as string).assigned_user_id); expect(JSON.parse(request?.[1]?.body as string)).toEqual({ assigned_user_id: employeeOption.id }); }); const urls = (fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).map(([url]) => url.toString()); expect(urls.some((url) => url.includes('/employees?limit=50&sort=name:asc'))).toBe(true); expect(urls.every((url) => !url.includes('/employee-portal'))).toBe(true); expect(document.body.textContent).toContain('No authoritative task priority field exists.'); });
});

describe('Owner Workspace project quick action', () => {
  it('displays a generated Client ID but submits the selected client UUID to the existing owner-scoped endpoint', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectsWorkspace />); await user.click(await screen.findByRole('button', { name: 'New project' })); await user.type(screen.getByLabelText('Project name'), 'Launch extension'); await user.selectOptions(await screen.findByLabelText('Project client'), clientOption.id); await user.click(screen.getByRole('button', { name: 'Create project' })); expect((await screen.findByRole('status')).textContent).toContain('Project created.'); await waitFor(() => { const request = (fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>).find(([url, init]) => url.toString().endsWith('/api/owner-workspace/projects') && init?.method === 'POST'); expect(JSON.parse(request?.[1]?.body as string)).toEqual({ client_id: clientOption.id, name: 'Launch extension' }); }); });
});
