import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import DashboardLayout from './layout';
import OwnerProjectsWorkspace from './components/OwnerProjectsWorkspace';
import OwnerProjectDetail from './components/OwnerProjectDetail';

process.env.NEXT_PUBLIC_ENGINE_URL = 'http://api.test';
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const asOf = '2026-07-21T12:00:00.000Z'; const project = { id: 'project-1', name: 'Launch', client: { id: 'client-1', name: 'Acme' }, status: { label: 'Project status', status: 'unavailable', source: 'crm_projects', window: 'current', asOf, reason: 'No authoritative project status field exists.' }, progress: { label: 'Project progress', status: 'unavailable', source: 'crm_projects', window: 'current', asOf, reason: 'No authoritative project progress field exists.' } }; const task = { id: 'task-1', name: 'Review', completed: false, assignee: null, project: { id: project.id, name: project.name, client: project.client }, status: { label: 'Task status', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'Completion is the only authoritative task-state field.' }, priority: { label: 'Task priority', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task priority field exists.' }, dueDate: { label: 'Task due date', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task due-date field exists.' }, progress: { label: 'Task progress', status: 'unavailable', source: 'crm_tasks', window: 'current', asOf, reason: 'No authoritative task progress field exists.' } };
const bootstrap = { success: true, data: { identity: { email: 'owner@example.test' }, capabilities: { overview: 'available' } } }; const dashboard = { success: true, data: { asOf, window: 'today', metrics: [], attention: { label: 'Attention', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable', items: [] }, recentActivity: { label: 'Activity', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable', items: [] }, health: { label: 'Health', status: 'unavailable', source: 'owner_workspace', window: 'current', asOf, reason: 'Unavailable' } } };
let nativeFetch = globalThis.fetch; afterEach(() => { cleanup(); globalThis.fetch = nativeFetch; vi.restoreAllMocks(); });
function ownerFetch() { const fetch = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = input.toString(); if (url.endsWith('/api/auth/refresh')) return json({ accessToken: 'token' }); if (url.endsWith('/bootstrap')) return json(bootstrap); if (url.endsWith('/dashboard')) return json(dashboard); if (url.includes('/projects/project-1/tasks/task-1')) return json({ success: true, data: task }); if (url.includes('/projects/project-1/tasks') && init?.method === 'POST') return json({ success: true, data: task }, 201); if (url.includes('/projects/project-1')) return json({ success: true, data: { project, tasks: { items: [task], pageInfo: { nextCursor: null, hasNextPage: false } } } }); if (url.includes('/projects')) return json({ success: true, data: { items: [project], pageInfo: { nextCursor: 'MQ', hasNextPage: true } } }); return json({ error: { message: 'Unexpected test request' } }, 500); }); globalThis.fetch = fetch as unknown as typeof fetch; return fetch; }
function workspace(node: React.ReactNode) { return render(<DashboardLayout>{node}</DashboardLayout>); }

describe('Owner Workspace projects', () => {
  it('renders a searchable, filterable, cursor-paginated project overview with unavailable progress fidelity', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectsWorkspace />); expect(await screen.findByRole('heading', { name: 'Project overview' })).toBeTruthy(); await user.type(screen.getByLabelText('Search projects'), 'Launch'); await user.type(screen.getByLabelText('Project client ID filter'), 'client-1'); await user.click(screen.getByRole('button', { name: 'Apply' })); await user.click(await screen.findByRole('button', { name: 'Next page' })); const urls = (fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).map(([url]) => url.toString()); expect(urls.some((url) => url.includes('q=Launch') && url.includes('client_id=client-1'))).toBe(true); expect(urls.some((url) => url.includes('cursor=MQ'))).toBe(true); expect(screen.getByText(/No authoritative project progress field exists/)).toBeTruthy(); });
  it('supports existing task creation, owner completion, and active-employee assignment without Employee Portal access', async () => { const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectDetail projectId="project-1" />); expect(await screen.findByRole('heading', { name: 'Launch' })).toBeTruthy(); await user.click(screen.getByRole('button', { name: 'Mark complete' })); expect((await screen.findByRole('status')).textContent).toContain('Task completed.'); await user.type(screen.getByLabelText('Task name'), 'Ship'); await user.click(screen.getByRole('button', { name: 'Create task' })); await user.click(screen.getByText('Task details and assignment')); await user.type(screen.getByLabelText('Employee ID for Review'), 'employee-1'); await user.click(screen.getByRole('button', { name: 'Assign employee' })); await waitFor(() => expect((fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>).some(([url, init]) => url.toString().includes('/tasks/task-1') && init?.method === 'PATCH')).toBe(true)); const urls = (fetch.mock.calls as unknown as Array<[RequestInfo | URL]>).map(([url]) => url.toString()); expect(urls.every((url) => !url.includes('/employee-portal'))).toBe(true); expect(document.body.textContent).toContain('No authoritative task priority field exists.'); });
});


describe('Owner Workspace project quick action', () => {
  it('creates a project through the existing owner-scoped endpoint and refreshes the overview', async () => {
    const user = userEvent.setup(); const fetch = ownerFetch(); workspace(<OwnerProjectsWorkspace />);
    await user.click(await screen.findByRole('button', { name: 'New project' }));
    await user.type(screen.getByLabelText('Project name'), 'Launch extension'); await user.type(screen.getByLabelText('Project client ID'), 'client-1');
    await user.click(screen.getByRole('button', { name: 'Create project' }));
    expect((await screen.findByRole('status')).textContent).toContain('Project created.');
    await waitFor(() => expect((fetch.mock.calls as unknown as Array<[RequestInfo | URL, RequestInit?]>).some(([url, init]) => url.toString().endsWith('/api/owner-workspace/projects') && init?.method === 'POST' && JSON.parse(init.body as string).name === 'Launch extension')).toBe(true));
  });
});