'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import type { ApiBody, OwnerClient, OwnerCreateProjectInput, OwnerPage, OwnerProject } from '../lib/owner-contracts';

export default function OwnerProjectsWorkspace() {
  const { request } = useOwnerWorkspace();
  const [query, setQuery] = useState(''); const [clientId, setClientId] = useState(''); const [appliedQuery, setAppliedQuery] = useState(''); const [appliedClientId, setAppliedClientId] = useState(''); const [sort, setSort] = useState('name:asc'); const [cursor, setCursor] = useState<string | null>(null);
  const [page, setPage] = useState<OwnerPage<OwnerProject> | null>(null); const [clients, setClients] = useState<OwnerClient[]>([]); const [newClientId, setNewClientId] = useState(''); const [projectName, setProjectName] = useState(''); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: '20', sort }); if (appliedQuery) params.set('q', appliedQuery); if (appliedClientId) params.set('client_id', appliedClientId); if (cursor) params.set('cursor', cursor); const body = await request<ApiBody<OwnerPage<OwnerProject>>>(`/api/owner-workspace/projects?${params}`); setPage(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load projects.'); } finally { setLoading(false); } }, [appliedClientId, appliedQuery, cursor, request, sort]);
  const loadClients = useCallback(async () => { try { const body = await request<ApiBody<OwnerPage<OwnerClient>>>('/api/owner-workspace/clients?limit=50&sort=name%3Aasc'); setClients(body.data.items); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load clients.'); } }, [request]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void loadClients(); }, [loadClients]);
  async function createProject(event: React.FormEvent) { event.preventDefault(); if (working) return; setWorking(true); setError(''); setNotice(''); try { const payload: OwnerCreateProjectInput = { client_id: newClientId, name: projectName.trim() }; await request('/api/owner-workspace/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); setNewClientId(''); setProjectName(''); setNotice('Project created.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Project creation failed.'); } finally { setWorking(false); } }
  return <section><header className="mb-7"><p className="text-sm font-medium text-cyan-300">Projects</p><h1 className="mt-1 text-3xl font-semibold">Project overview</h1><p className="mt-2 text-sm text-slate-300">Create and manage projects scoped to your authenticated clients.</p></header>
    {error && <div role="alert" className="mb-5 rounded-xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-100">{error}<button type="button" onClick={() => void load()} className="ml-3 underline">Try again</button></div>}{notice && <p role="status" className="mb-5 rounded-xl border border-cyan-300/30 bg-cyan-950/30 p-4 text-sm text-cyan-100">{notice}</p>}
    <form id="create-project" onSubmit={(event) => void createProject(event)} className="mb-6 scroll-mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold">Create project</h2><div className="mt-3 flex flex-wrap gap-3"><label className="text-sm">Client<select required aria-label="Project client" value={newClientId} onChange={(event) => setNewClientId(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300"><option value="">Select a client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="text-sm">Project name<input required aria-label="Project name" value={projectName} onChange={(event) => setProjectName(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300" /></label><button disabled={working || !newClientId || !projectName.trim()} className="rounded-lg bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 focus:outline-none focus:ring-2 focus:ring-cyan-100 disabled:cursor-not-allowed disabled:opacity-60">{working ? 'Creating…' : 'Create project'}</button></div></form>
    <form className="mb-5 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); setCursor(null); setAppliedQuery(query.trim()); setAppliedClientId(clientId); }}><label className="text-sm">Search <input aria-label="Search projects" value={query} onChange={(event) => setQuery(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300" /></label><label className="text-sm">Client filter<select aria-label="Project client filter" value={clientId} onChange={(event) => setClientId(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300"><option value="">All clients</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="text-sm">Sort <select value={sort} onChange={(event) => { setCursor(null); setSort(event.target.value); }} className="ml-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300"><option value="name:asc">Name A–Z</option><option value="name:desc">Name Z–A</option></select></label><button className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:border-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-300">Apply</button></form>
    <section aria-busy={loading} className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70">{loading ? <div className="space-y-3 p-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-12 animate-pulse rounded bg-slate-800" />)}</div> : !page?.items.length ? <p className="p-5 text-sm text-slate-300">No projects match the selected filters.</p> : <ul className="divide-y divide-slate-800">{page.items.map((project) => <li key={project.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium text-white">{project.name}</p><p className="mt-1 text-sm text-slate-400">Client: {project.client?.name || 'Unavailable'}</p><p className="mt-1 text-xs text-slate-500">{project.progress.reason}</p></div><Link href={`/dashboard/projects/${project.id}`} className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:border-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-300">View project</Link></li>)}</ul>}<div className="flex justify-end border-t border-slate-800 p-4">{page?.pageInfo.hasNextPage && <button onClick={() => setCursor(page.pageInfo.nextCursor)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:border-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-300">Next page</button>}</div></section>
  </section>;
}
