'use client';

import { useCallback, useEffect, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import type { ApiBody, OwnerAuditEvent, OwnerPage } from '../lib/owner-contracts';

export default function OwnerAuditWorkspace() {
  const { request } = useOwnerWorkspace(); const [category, setCategory] = useState('all'); const [cursor, setCursor] = useState<string | null>(null); const [page, setPage] = useState<OwnerPage<OwnerAuditEvent> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: '20', category }); if (cursor) params.set('cursor', cursor); const body = await request<ApiBody<OwnerPage<OwnerAuditEvent>>>(`/api/owner-workspace/audit?${params}`); setPage(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load audit history.'); } finally { setLoading(false); } }, [category, cursor, request]);
  useEffect(() => { void load(); }, [load]);
  return <section><header className="mb-7"><p className="text-sm text-cyan-300">Audit</p><h1 className="text-3xl font-semibold">Owner-attributable audit history</h1><p className="mt-2 text-sm text-slate-300">Only existing events directly attributable to this owner are shown. Sensitive event details are redacted.</p></header><label>Category <select aria-label="Audit category" value={category} onChange={(event) => { setCursor(null); setCategory(event.target.value); }} className="ml-2 rounded border border-slate-700 bg-slate-900 px-2 py-1"><option value="all">All available</option><option value="security">Security</option><option value="invitations">Invitations</option><option value="employees">Employees</option><option value="automation">Automation</option><option value="documents">Documents</option></select></label>{error && <p role="alert" className="mt-4 rounded border border-red-400/30 p-3">{error}<button onClick={() => void load()} className="ml-3 underline">Try again</button></p>}<section aria-busy={loading} className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70">{loading ? <div className="space-y-3 p-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-12 animate-pulse rounded bg-slate-800" />)}</div> : !page?.items.length ? <p className="p-5 text-sm text-slate-300">No owner-attributable events are available for this category.</p> : <ul className="divide-y divide-slate-800">{page.items.map((event) => <li key={event.id} className="p-4"><p className="font-medium">{event.label}</p><p className="mt-1 text-sm text-slate-400">{event.success ? 'Succeeded' : 'Failed'} · <time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time></p></li>)}</ul>}<div className="flex justify-end border-t border-slate-800 p-4">{page?.pageInfo.hasNextPage && <button onClick={() => setCursor(page.pageInfo.nextCursor)} className="rounded border border-slate-700 px-3 py-1 focus:outline-none focus:ring-2 focus:ring-cyan-300">Next page</button>}</div></section></section>;
}
