'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import OwnerGlobalSearch from './OwnerGlobalSearch';
import OwnerWorkspaceControls from './OwnerWorkspaceControls';

const ownerNavigation = [{ href: '/dashboard', label: 'Overview' }, { href: '/dashboard/approvals', label: 'Sales approvals' }, { href: '/dashboard/crm', label: 'CRM' }, { href: '/dashboard/clients', label: 'Clients' }, { href: '/dashboard/projects', label: 'Projects' }, { href: '/dashboard/employees', label: 'Employees' }, { href: '/dashboard/communications', label: 'Communications' }, { href: '/dashboard/automations', label: 'Automations' }, { href: '/dashboard/finance', label: 'Finance' }, { href: '/dashboard/documents', label: 'Documents' }, { href: '/dashboard/audit', label: 'Audit' }, { href: '/dashboard/settings', label: 'Settings' }];
const financeNavigation = [{ href: '/dashboard/finance', label: 'Finance' }];

export default function OwnerWorkspaceShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname() || ''; const { bootstrap, workspaceKind, canManageBillingProfile, loading, refresh, logout } = useOwnerWorkspace(); const [drawerOpen, setDrawerOpen] = useState(false); const triggerRef = useRef<HTMLButtonElement>(null); const closeRef = useRef<HTMLButtonElement>(null);
  const financeOnly = workspaceKind === 'finance' && !canManageBillingProfile; const navigation = financeOnly ? financeNavigation : ownerNavigation; const workspaceLabel = financeOnly ? 'Finance workspace' : 'Owner Workspace';
  useEffect(() => { if (drawerOpen) closeRef.current?.focus(); else triggerRef.current?.focus(); }, [drawerOpen]);
  const closeDrawer = () => setDrawerOpen(false);
  const navLinks = (mobile = false) => <nav aria-label={workspaceLabel} className={mobile ? 'space-y-2' : 'space-y-1'}>{navigation.map((item) => { const active = pathname === item.href || (item.href !== '/dashboard' && pathname.startsWith(`${item.href}/`)); return <Link key={item.href} href={item.href} aria-current={active ? 'page' : undefined} onClick={closeDrawer} className={`block rounded-lg px-3 py-2 text-sm font-semibold outline-none transition focus:ring-2 focus:ring-cyan-300 ${active ? 'bg-cyan-400/15 text-cyan-100' : 'text-slate-300 hover:bg-slate-800 hover:text-white'}`}>{item.label}</Link>; })}</nav>;
  return <div className="min-h-screen bg-slate-950 text-slate-100"><a href="#owner-workspace-main" className="sr-only z-[70] rounded bg-cyan-200 px-3 py-2 text-slate-950 focus:not-sr-only focus:fixed focus:left-4 focus:top-4">Skip to dashboard content</a><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-slate-800 bg-slate-950 p-5 md:block"><Link href={financeOnly ? '/dashboard/finance' : '/'} className="text-lg font-bold tracking-wide text-white">JARVIS PRIME</Link><p className="mt-1 text-xs text-slate-500">{workspaceLabel}</p><div className="mt-10">{navLinks()}</div></aside><header className="border-b border-slate-800 bg-slate-950/95 px-4 py-4 md:ml-64 md:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex items-center gap-3"><button ref={triggerRef} onClick={() => setDrawerOpen(true)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm md:hidden focus:outline-none focus:ring-2 focus:ring-cyan-300" aria-label="Open navigation" aria-expanded={drawerOpen}>Menu</button><div><p className="text-xs text-slate-500">{workspaceLabel}</p><p className="font-medium text-white">{bootstrap?.identity?.email || 'Loading account…'}</p></div></div><div className="flex items-center gap-2">{!financeOnly && <OwnerGlobalSearch />}<OwnerWorkspaceControls loading={loading} onRefresh={refresh} onLogout={logout} /></div></div></header><main id="owner-workspace-main" className="px-4 py-7 md:ml-64 md:px-8" aria-busy={loading && !bootstrap}><div className="mx-auto max-w-7xl">{children}</div></main>{drawerOpen && <div role="dialog" aria-modal="true" aria-label={`${workspaceLabel} navigation`} onKeyDown={(event) => { if (event.key === 'Escape') closeDrawer(); }} className="fixed inset-0 z-[60] bg-slate-950/70 p-4 md:hidden"><aside className="h-full w-72 rounded-2xl border border-slate-700 bg-slate-950 p-5 shadow-2xl"><div className="flex items-center justify-between"><p className="font-semibold">Navigation</p><button ref={closeRef} onClick={closeDrawer} className="rounded-lg border border-slate-700 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-cyan-300" aria-label="Close navigation">Close</button></div><div className="mt-8">{navLinks(true)}</div></aside></div>}</div>;
}
