'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import type { ApiBody, OwnerEmployeeDetail as EmployeeDetail } from '../lib/owner-contracts';

export default function OwnerEmployeeDetail({ employeeId }: { employeeId: string }) {
  const { request } = useOwnerWorkspace(); const [detail, setDetail] = useState<EmployeeDetail | null>(null); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const suffix = cursor ? `?cursor=${encodeURIComponent(cursor)}&limit=20` : '?limit=20'; const body = await request<ApiBody<EmployeeDetail>>(`/api/owner-workspace/employees/${employeeId}${suffix}`); setDetail(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load employee details.'); } finally { setLoading(false); } }, [cursor, employeeId, request]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <section aria-busy="true" className="space-y-5"><div className="h-10 w-64 animate-pulse rounded bg-slate-800" />{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-2xl bg-slate-900" />)}</section>;
  if (error && !detail) return <section role="alert" className="rounded-2xl border border-red-400/30 bg-red-950/30 p-5"><h1 className="text-xl font-semibold">Employee could not load</h1><p className="mt-2 text-sm">{error}</p><button onClick={() => void load()} className="mt-4 underline">Try again</button></section>;
  const employee = detail?.employee; const assignments = detail?.assignments.items || [];
  return <section><Link href="/dashboard/employees" className="text-sm text-cyan-300 hover:underline">← Employees</Link><header className="mt-4"><p className="text-sm font-medium text-cyan-300">Employee details</p><h1 className="mt-1 text-3xl font-semibold">{employee?.fullName || employee?.email}</h1><p className="mt-2 text-sm text-slate-300">{employee?.email}</p></header>{error && <div role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-100">{error}<button onClick={() => void load()} className="ml-3 underline">Try again</button></div>}<div className="mt-6 grid gap-4 md:grid-cols-3"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Current workload</h2><p className="mt-2 text-sm">{employee?.workload.open} open · {employee?.workload.completed} completed · {employee?.workload.assigned} assigned</p><p className="mt-2 text-xs text-slate-400">{employee?.workload.definition}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Availability</h2><p className="mt-2 text-sm text-slate-300">Unavailable — {employee?.availability.reason}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Performance summary</h2><p className="mt-2 text-sm text-slate-300">Unavailable — {employee?.performance.reason}</p></section></div><section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold">Current project participation</h2>{!detail?.projects.length ? <p className="mt-3 text-sm text-slate-300">No projects are referenced by the current assignment page.</p> : <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{detail.projects.map((project) => <li key={project.id}>{project.name} {project.client ? `· ${project.client.name}` : ''}</li>)}</ul>}</section><section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold">Current assignments</h2>{!assignments.length ? <p className="mt-3 text-sm text-slate-300">No direct task assignments are recorded.</p> : <ul className="mt-4 divide-y divide-slate-800">{assignments.map((task) => <li key={task.id} className="py-3"><p className="font-medium">{task.name}</p><p className="text-sm text-slate-400">{task.project.name} · {task.completed ? 'Completed' : 'Open'}</p></li>)}</ul>}<div className="mt-4 flex justify-end">{detail?.assignments.pageInfo.hasNextPage && <button onClick={() => setCursor(detail.assignments.pageInfo.nextCursor)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-cyan-300">Next assignments</button>}</div></section><p className="mt-6 text-sm text-slate-400">Employee creation, credential lifecycle, password reset, role changes, activation, and deactivation require future approved implementation.</p></section>;
}
