'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import type { ApiBody, OwnerProjectDetail as ProjectDetail } from '../lib/owner-contracts';

export default function OwnerProjectDetail({ projectId }: { projectId: string }) {
  const { request } = useOwnerWorkspace(); const [detail, setDetail] = useState<ProjectDetail | null>(null); const [cursor, setCursor] = useState<string | null>(null); const [taskName, setTaskName] = useState(''); const [selectedTask, setSelectedTask] = useState<string | null>(null); const [employeeId, setEmployeeId] = useState(''); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const suffix = cursor ? `?cursor=${encodeURIComponent(cursor)}&limit=20` : '?limit=20'; const body = await request<ApiBody<ProjectDetail>>(`/api/owner-workspace/projects/${projectId}${suffix}`); setDetail(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load this project.'); } finally { setLoading(false); } }, [cursor, projectId, request]);
  useEffect(() => { void load(); }, [load]);
  async function updateTask(taskId: string, values: Record<string, unknown>, message: string) { setWorking(true); setError(''); setNotice(''); try { await request(`/api/owner-workspace/projects/${projectId}/tasks/${taskId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); setNotice(message); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Task update failed.'); } finally { setWorking(false); } }
  async function createTask() { setWorking(true); setError(''); setNotice(''); try { await request(`/api/owner-workspace/projects/${projectId}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: taskName }) }); setTaskName(''); setNotice('Task created.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Task creation failed.'); } finally { setWorking(false); } }
  if (loading) return <section aria-busy="true" className="space-y-5"><div className="h-10 w-64 animate-pulse rounded bg-slate-800" />{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-2xl bg-slate-900" />)}</section>;
  if (error && !detail) return <section role="alert" className="rounded-2xl border border-red-400/30 bg-red-950/30 p-5"><h1 className="text-xl font-semibold">Project could not load</h1><p className="mt-2 text-sm">{error}</p><button onClick={() => void load()} className="mt-4 underline">Try again</button></section>;
  const project = detail?.project; const tasks = detail?.tasks.items || [];
  return <section><Link href="/dashboard/projects" className="text-sm text-cyan-300 hover:underline">← Projects</Link><header className="mt-4"><p className="text-sm font-medium text-cyan-300">Project details</p><h1 className="mt-1 text-3xl font-semibold">{project?.name}</h1><p className="mt-2 text-sm text-slate-300">Assigned client: {project?.client?.name || 'Unavailable'}</p></header>{error && <div role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-100">{error}<button onClick={() => void load()} className="ml-3 underline">Try again</button></div>}{notice && <p role="status" className="mt-5 rounded-xl border border-cyan-300/30 bg-cyan-950/30 p-4 text-sm text-cyan-100">{notice}</p>}
    <div className="mt-6 grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Project status</h2><p className="mt-2 text-sm text-slate-300">Unavailable — {project?.status.reason}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Project progress</h2><p className="mt-2 text-sm text-slate-300">Unavailable — {project?.progress.reason}</p></section></div>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold">Create task</h2><form className="mt-3 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); void createTask(); }}><label className="text-sm">Task name <input required value={taskName} onChange={(event) => setTaskName(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300" /></label><button disabled={working} className="rounded-lg bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 focus:outline-none focus:ring-2 focus:ring-cyan-100 disabled:opacity-60">Create task</button></form></section>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold">Task overview</h2>{!tasks.length ? <p className="mt-3 text-sm text-slate-300">No tasks are assigned to this project.</p> : <ul className="mt-4 divide-y divide-slate-800">{tasks.map((task) => <li key={task.id} className="py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{task.name}</p><p className="mt-1 text-sm text-slate-400">Completion: {task.completed ? 'Completed' : 'Open'} · Assignee: {task.assignee?.fullName || task.assignee?.email || 'Unassigned'}</p></div><button disabled={working} onClick={() => void updateTask(task.id, { completed: !task.completed }, task.completed ? 'Task reopened.' : 'Task completed.')} className="rounded-lg border border-slate-700 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-cyan-300">{task.completed ? 'Reopen' : 'Mark complete'}</button></div><details className="mt-3 text-sm"><summary className="cursor-pointer text-cyan-300">Task details and assignment</summary><p className="mt-3 text-slate-300">Status: unavailable — {task.status.reason}</p><p className="mt-1 text-slate-300">Priority: unavailable — {task.priority.reason}</p><p className="mt-1 text-slate-300">Due date: unavailable — {task.dueDate.reason}</p><p className="mt-1 text-slate-300">Progress: unavailable — {task.progress.reason}</p><div className="mt-3 flex flex-wrap gap-2"><label>Employee ID <input aria-label={`Employee ID for ${task.name}`} value={selectedTask === task.id ? employeeId : ''} onFocus={() => setSelectedTask(task.id)} onChange={(event) => { setSelectedTask(task.id); setEmployeeId(event.target.value); }} className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-1 text-white focus:outline-none focus:ring-2 focus:ring-cyan-300" /></label><button disabled={working || selectedTask !== task.id || !employeeId} onClick={() => void updateTask(task.id, { assigned_user_id: employeeId }, 'Task assignee updated.')} className="rounded border border-slate-700 px-2 py-1 focus:outline-none focus:ring-2 focus:ring-cyan-300">Assign employee</button></div></details></li>)}</ul>}<div className="mt-4 flex justify-end">{detail?.tasks.pageInfo.hasNextPage && <button onClick={() => setCursor(detail.tasks.pageInfo.nextCursor)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-cyan-300">Next tasks</button>}</div></section>
  </section>;
}
