'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import type { ApiBody, OwnerClient, OwnerDocument, OwnerDocumentType, OwnerPage, OwnerProject } from '../lib/owner-contracts';

export default function OwnerDocumentsWorkspace() {
  const { request } = useOwnerWorkspace(); const [page, setPage] = useState<OwnerPage<OwnerDocument> | null>(null); const [clients, setClients] = useState<OwnerClient[]>([]); const [projects, setProjects] = useState<OwnerProject[]>([]); const [q, setQ] = useState(''); const [appliedQ, setAppliedQ] = useState(''); const [visibility, setVisibility] = useState('all'); const [sort, setSort] = useState('created_at:desc'); const [cursor, setCursor] = useState<string | null>(null);
  const [clientId, setClientId] = useState(''); const [projectId, setProjectId] = useState(''); const [title, setTitle] = useState(''); const [documentType, setDocumentType] = useState<OwnerDocumentType>('deliverable'); const [file, setFile] = useState<File | null>(null); const [fileKey, setFileKey] = useState(0); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: '20', sort, visibility }); if (appliedQ) params.set('q', appliedQ); if (cursor) params.set('cursor', cursor); const body = await request<ApiBody<OwnerPage<OwnerDocument>>>(`/api/owner-workspace/documents?${params}`); setPage(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load documents.'); } finally { setLoading(false); } }, [appliedQ, cursor, request, sort, visibility]);
  const loadOptions = useCallback(async () => { try { const [clientBody, projectBody] = await Promise.all([request<ApiBody<OwnerPage<OwnerClient>>>('/api/owner-workspace/clients?limit=50&sort=name%3Aasc'), request<ApiBody<OwnerPage<OwnerProject>>>('/api/owner-workspace/projects?limit=50&sort=name%3Aasc')]); setClients(clientBody.data.items); setProjects(projectBody.data.items); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load document scope options.'); } }, [request]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void loadOptions(); }, [loadOptions]);
  async function publish(event: React.FormEvent) { event.preventDefault(); if (working) return; if (!file) { setError('Select one permitted document file.'); return; } setWorking(true); setError(''); setNotice(''); try { const body = new FormData(); body.set('client_id', clientId); body.set('title', title.trim()); body.set('document_type', documentType); if (projectId) body.set('project_id', projectId); body.set('file', file); await request('/api/owner-workspace/documents', { method: 'POST', body }); setTitle(''); setClientId(''); setProjectId(''); setFile(null); setFileKey((value) => value + 1); setNotice('Private document published to the selected client.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Document publication failed.'); } finally { setWorking(false); } }
  const scopedProjects = projects.filter((project) => !clientId || project.client?.id === clientId);
  return <section><header className="mb-7"><p className="text-sm font-medium text-cyan-300">Documents</p><h1 className="mt-1 text-3xl font-semibold">Client Portal documents</h1><p className="mt-2 text-sm text-slate-300">Private document metadata and visibility are scoped to your clients. Downloads and storage paths are never shown here.</p></header>
    <form className="mb-5 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); setCursor(null); setAppliedQ(q.trim()); }}><label>Search <input aria-label="Search documents" value={q} onChange={(event) => setQ(event.target.value)} className="ml-2 rounded border border-slate-700 bg-slate-900 px-2 py-1" /></label><label>Visibility <select aria-label="Document visibility" value={visibility} onChange={(event) => { setCursor(null); setVisibility(event.target.value); }} className="ml-2 rounded border border-slate-700 bg-slate-900 px-2 py-1"><option value="all">All</option><option value="visible">Visible</option><option value="revoked">Revoked</option></select></label><label>Sort <select aria-label="Document sort" value={sort} onChange={(event) => { setCursor(null); setSort(event.target.value); }} className="ml-2 rounded border border-slate-700 bg-slate-900 px-2 py-1"><option value="created_at:desc">Newest</option><option value="title:asc">Title A–Z</option></select></label><button className="rounded border border-slate-700 px-3 py-1 focus:outline-none focus:ring-2 focus:ring-cyan-300">Apply</button></form>
    {error && <p role="alert" className="mb-4 rounded border border-red-400/30 p-3">{error}<button type="button" onClick={() => void load()} className="ml-3 underline">Try again</button></p>}{notice && <p role="status" className="mb-4 rounded border border-cyan-300/30 p-3">{notice}</p>}
    <form id="upload-document" onSubmit={(event) => void publish(event)} className="mb-6 scroll-mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Publish document</h2><div className="mt-3 flex flex-wrap gap-3"><label>Client<select required aria-label="Document client" value={clientId} onChange={(event) => { setClientId(event.target.value); setProjectId(''); }} className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-1"><option value="">Select a client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Project (optional)<select aria-label="Document project" value={projectId} onChange={(event) => setProjectId(event.target.value)} className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-1"><option value="">No project</option>{scopedProjects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Title <input required value={title} onChange={(event) => setTitle(event.target.value)} className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-1" /></label><label>Type <select value={documentType} onChange={(event) => setDocumentType(event.target.value as OwnerDocumentType)} className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-1"><option value="deliverable">Deliverable</option><option value="report">Report</option></select></label><label>File <input key={fileKey} required aria-label="Document file" type="file" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><button disabled={working || !clientId || !title.trim() || !file} className="rounded bg-cyan-300 px-3 py-1 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-60">{working ? 'Publishing…' : 'Publish'}</button></div></form>
    <section aria-busy={loading} className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70">{loading ? <div className="space-y-3 p-5">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-11 animate-pulse rounded bg-slate-800" />)}</div> : !page?.items.length ? <p className="p-5 text-sm text-slate-300">No documents match the selected filters.</p> : <ul className="divide-y divide-slate-800">{page.items.map((document) => <li key={document.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{document.title}</p><p className="text-sm text-slate-400">{document.documentType} · {document.client?.name || 'Client unavailable'}{document.project ? ` · ${document.project.name}` : ''} · {document.visibility}</p></div><Link href={`/dashboard/documents/${document.id}`} className="rounded border border-slate-700 px-3 py-1 focus:outline-none focus:ring-2 focus:ring-cyan-300">View document</Link></li>)}</ul>}<div className="flex justify-end border-t border-slate-800 p-4">{page?.pageInfo.hasNextPage && <button onClick={() => setCursor(page.pageInfo.nextCursor)} className="rounded border border-slate-700 px-3 py-1 focus:outline-none focus:ring-2 focus:ring-cyan-300">Next page</button>}</div></section>
  </section>;
}
