'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useOwnerWorkspace } from './OwnerSessionBoundary';
import type { ApiBody, OwnerCreateTaskInput, OwnerPage, OwnerProject, OwnerTask, OwnerUpdateTaskInput } from '../lib/owner-contracts';

export default function OwnerTasksWorkspace() {
  const { request } = useOwnerWorkspace(); const [page, setPage] = useState<OwnerPage<OwnerTask> | null>(null); const [projects, setProjects] = useState<OwnerProject[]>([]); const [query, setQuery] = useState(''); const [appliedQuery, setAppliedQuery] = useState(''); const [projectFilter, setProjectFilter] = useState(''); const [appliedProject, setAppliedProject] = useState(''); const [cursor, setCursor] = useState<string | null>(null); const [newProjectId, setNewProjectId] = useState(''); const [newTaskName, setNewTaskName] = useState(''); const [taskNames, setTaskNames] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: '20', sort: 'name:asc' }); if (appliedQuery) params.set('q', appliedQuery); if (appliedProject) params.set('project_id', appliedProject); if (cursor) params.set('cursor', cursor); const body = await request<ApiBody<OwnerPage<OwnerTask>>>(`/api/owner-workspace/tasks?${params}`); setPage(body.data); setTaskNames(Object.fromEntries(body.data.items.map((task) => [task.id, task.name]))); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load tasks.'); } finally { setLoading(false); } }, [appliedProject, appliedQuery, cursor, request]);
  const loadProjects = useCallback(async () => { try { const body = await request<ApiBody<OwnerPage<OwnerProject>>>('/api/owner-workspace/projects?limit=50&sort=name%3Aasc'); setProjects(body.data.items); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load projects.'); } }, [request]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void loadProjects(); }, [loadProjects]);
  async function createTask(event: React.FormEvent) { event.preventDefault(); if (working) return; setWorking(true); setError(''); setNotice(''); try { const payload: OwnerCreateTaskInput = { name: newTaskName.trim() }; await request(`/api/owner-workspace/projects/${newProjectId}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); setNewTaskName(''); setNotice('Task created.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Task creation failed.'); } finally { setWorking(false); } }
  async function updateTask(task: OwnerTask, event: React.FormEvent) { event.preventDefault(); if (working) return; setWorking(true); setError(''); setNotice(''); try { const payload: OwnerUpdateTaskInput = { name: (taskNames[task.id] || '').trim() }; await request(`/api/owner-workspace/projects/${task.project.id}/tasks/${task.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); setNotice('Task name updated.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Task update failed.'); } finally { setWorking(false); } }
  return <section><header className="mb-7"><p className="text-sm font-medium text-cyan-300">Tasks</p><h1 className="mt-1 text-3xl font-semibold">Task workspace</h1><p className="mt-2 text-sm text-slate-300">Create and rename tasks through their scoped owner project.</p></header>
    {error && <div role="alert" className="mb-5 rounded-xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-100">{error}<button type="button" onClick={() => void load()} className="ml-3 underline">Try again</button></div>}{notice && <p role="status" className="mb-5 rounded-xl border border-cyan-300/30 bg-cyan-950/30 p-4 text-sm text-cyan-100">{notice}</p>}
    <form id="create-task" onSubmit={(event) => void createTask(event)} className="mb-6 scroll-mt-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold">Create task</h2><div className="mt-3 flex flex-wrap gap-3"><label className="text-sm">Project<select required aria-label="Task project" value={newProjectId} onChange={(event) => setNewProjectId(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Select a project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}{project.client ? ` — ${project.client.name}` : ''}</option>)}</select></label><label className="text-sm">Task name<input required aria-label="New task name" value={newTaskName} onChange={(event) => setNewTaskName(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label><button disabled={working || !newProjectId || !newTaskName.trim()} className="rounded-lg bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-60">{working ? 'Creating…' : 'Create task'}</button></div></form>
    <form className="mb-5 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); setCursor(null); setAppliedQuery(query.trim()); setAppliedProject(projectFilter); }}><label className="text-sm">Search<input aria-label="Search tasks" value={query} onChange={(event) => setQuery(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white" /></label><label className="text-sm">Project filter<select aria-label="Task project filter" value={projectFilter} onChange={(event) => setProjectFilter(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white"><option value="">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button className="rounded-lg border border-slate-700 px-3 py-2 text-sm">Apply</button></form>
    <section aria-busy={loading} className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/70">{loading ? <div className="space-y-3 p-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-14 animate-pulse rounded bg-slate-800" />)}</div> : !page?.items.length ? <p className="p-5 text-sm text-slate-300">No tasks match the selected filters.</p> : <ul className="divide-y divide-slate-800">{page.items.map((task) => <li key={task.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{task.name}</p><p className="text-sm text-slate-400">{task.project.name} · {task.project.client?.name || 'Client unavailable'} · {task.completed ? 'Completed' : 'Open'}</p></div><Link href={`/dashboard/projects/${task.project.id}`} className="rounded border border-slate-700 px-3 py-2 text-sm">View project</Link></div><form className="mt-3 flex flex-wrap gap-2" onSubmit={(event) => void updateTask(task, event)}><label className="text-sm">Task name<input required aria-label={`Edit task name for ${task.name}`} value={taskNames[task.id] || ''} onChange={(event) => setTaskNames((values) => ({ ...values, [task.id]: event.target.value }))} className="ml-2 rounded border border-slate-700 bg-slate-950 px-2 py-1 text-white" /></label><button disabled={working || !taskNames[task.id]?.trim() || taskNames[task.id]?.trim() === task.name} className="rounded border border-slate-700 px-3 py-1 text-sm disabled:opacity-60">Save task name</button></form></li>)}</ul>}<div className="flex justify-end border-t border-slate-800 p-4">{page?.pageInfo.hasNextPage && <button onClick={() => setCursor(page.pageInfo.nextCursor)} className="rounded border border-slate-700 px-3 py-2 text-sm">Next page</button>}</div></section>
  </section>;
}
